apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: tp2
  labels:
    app: nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx-busybox
  ports:
  - name: http
    port: 8081
    targetPort: 80
    protocol: TCP

