name: Secret Demo

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar se API_KEY existe
        run: |
          if [ -n "${{ secrets.API_KEY }}" ]; then
            echo "API_KEY configurado"
          else
            echo "API_KEY N√ÉO configurado"
          fi
